# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Build and publish app release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    env:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      APPSTORE_TOKEN: ${{ secrets.APPSTORE_TOKEN }}

    steps:
      - name: Check actor permission
        uses: skjnldsv/check-actor-permission@69e92a3c4711150929bca9fcf34448c5bf5526e7 # v3.0
        with:
          require: write

      - name: Set app env
        run: |
          # Split and keep last
          echo "APP_VERSION_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          path: app-src

      - name: Get app id and version
        id: app-data
        run: |
          echo "APP_NAME=$(sed -n 's/.*<id>\(.*\)<\/id>.*/\1/p' app-src/appinfo/info.xml | xargs)" >> $GITHUB_ENV
          echo "APP_VERSION=$(sed -n 's/.*<version>\(.*\)<\/version>.*/\1/p' app-src/appinfo/info.xml | xargs)" >> $GITHUB_ENV
          echo "NC_MIN_VERSION=$(grep -oP '(?<=nextcloud min-version=").*?(?=")' app-src/appinfo/info.xml)" >> $GITHUB_ENV

      - name: Validate app version against tag
        run: |
          [ "${{ env.APP_VERSION_TAG }}" = "v${{ env.APP_VERSION }}" ]

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@06d6baf7d8f41934ab630e97d9e6c0bc9c9ac5e4 # v3
        id: versions
        # Continue if no package.json
        continue-on-error: true
        with:
          path: app-src
          fallbackNode: '^24'
          fallbackNpm: '^11.3'

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        # Skip if no package.json
        if: ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}
          package-manager-cache: false

      - name: Get php version
        id: php-versions
        uses: icewind1991/nextcloud-version-matrix@8a7bac6300b2f0f3100088b297995a229558ddba # v1.3.2
        with:
          filename: app-src/appinfo/info.xml

      - name: Set up php ${{ steps.php-versions.outputs.php-min }}
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: ${{ steps.php-versions.outputs.php-min }}
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check composer.json
        id: check_composer
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: "app-src/composer.json"

      - name: Install composer dependencies
        if: steps.check_composer.outputs.files_exists == 'true'
        run: |
          cd app-src
          composer install --no-dev

      - name: Build ${{ env.APP_NAME }}
        # Skip if no package.json
        if: ${{ steps.versions.outputs.nodeVersion }}
        env:
          CYPRESS_INSTALL_BINARY: 0
        run: |
          cd app-src
          npm install --legacy-peer-deps
          npm run build --if-present

      - name: Package ${{ env.APP_NAME }} ${{ env.APP_VERSION }} with makefile
        run: |
          cd app-src
          make appstore

      - name: Check server download link for ${{ env.NC_MIN_VERSION }}
        if: ${{ env.APP_PRIVATE_KEY != '' }}
        run: |
          NCVERSION='${{ env.NC_MIN_VERSION }}'
          DOWNLOAD_URL=$(curl -s "https://updates.nextcloud.com/updater_server/latest?channel=beta&version=$NCVERSION" | jq -r '.downloads.zip[0]')
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV

      - name: Download server ${{ env.NC_MIN_VERSION }}
        continue-on-error: true
        id: server-download
        if: ${{ env.APP_PRIVATE_KEY != '' && env.DOWNLOAD_URL != 'null' }}
        run: |
          echo "Downloading release tarball from $DOWNLOAD_URL"
          wget $DOWNLOAD_URL -O nextcloud.zip
          unzip nextcloud.zip

      - name: Checkout server master fallback
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: ${{ env.APP_PRIVATE_KEY != '' && steps.server-download.outcome != 'success' }}
        with:
          persist-credentials: false
          submodules: true
          repository: nextcloud/server
          path: nextcloud

      - name: Sign app
        if: ${{ env.APP_PRIVATE_KEY != '' }}
        run: |
          # Extracting release
          cd app-src/build/artifacts
          tar -xvf ${{ env.APP_NAME }}.tar.gz
          cd ../../../
          # Setting up keys
          echo '${{ env.APP_PRIVATE_KEY }}' > ${{ env.APP_NAME }}.key
          wget --quiet "https://github.com/nextcloud/app-certificate-requests/raw/master/${{ env.APP_NAME }}/${{ env.APP_NAME }}.crt"
          # Signing
          php nextcloud/occ integrity:sign-app --privateKey=./${{ env.APP_NAME }}.key --certificate=./${{ env.APP_NAME }}.crt --path=$(pwd)/app-src/build/artifacts/${{ env.APP_NAME }}
          # Rebuilding archives
          cd app-src/build/artifacts
          tar -zcvf ${{ env.APP_NAME }}.tar.gz --owner=www-data --group=www-data ${{ env.APP_NAME }}
          zip -r ${{ env.APP_NAME }}.zip ${{ env.APP_NAME }}

      - name: Attach tarball to github release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app-src/build/artifacts/${{ env.APP_NAME }}.tar.gz
          asset_name: ${{ env.APP_NAME }}-${{ env.APP_VERSION_TAG }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

      - name: Attach zip to github release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app-src/build/artifacts/${{ env.APP_NAME }}.zip
          asset_name: ${{ env.APP_NAME }}-${{ env.APP_VERSION_TAG }}.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload app to Nextcloud appstore
        if: ${{ env.APPSTORE_TOKEN != '' && env.APP_PRIVATE_KEY != '' }}
        uses: nextcloud-releases/nextcloud-appstore-push-action@a011fe619bcf6e77ddebc96f9908e1af4071b9c1 # v1.0.3
        with:
          app_name: ${{ env.APP_NAME }}
          appstore_token: ${{ env.APPSTORE_TOKEN }}
          download_url: https://github.com/${{ github.repository }}/releases/download/${{ env.APP_VERSION_TAG }}/${{ env.APP_NAME }}-${{ env.APP_VERSION_TAG }}.tar.gz
          app_private_key: ${{ env.APP_PRIVATE_KEY }}
