name: Artifact

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get Info
        run: |
          echo "version=$(grep -Eo '[0-9]+(\.[0-9]+)+' CHANGELOG.md | head -n 1)" >> $GITHUB_OUTPUT
        id: info
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          cwd=$(pwd)
          git submodule update --init --recursive
          npm install
          npm run build
          composer install --no-dev --optimize-autoloader
          mkdir -p cad_viewer
          rsync -av --exclude='cad_viewer' . cad_viewer
          cd cad_viewer
          rm -rf ./.github/
          rm -rf ./.git/
          rm -rf ./assets/document-templates/.git
          rm -rf ./assets/document-formats/.git
          rm -rf ./node_modules/
          rm -rf ./src/
          rm -f ./.eslintrc.js
          rm -f ./.gitignore
          rm -f ./.gitmodules
          rm -f ./.stylelintrc.json
          rm -f ./composer.json
          rm -f ./composer.lock
          rm -f ./npm-shrinkwrap.json
          rm -f ./package.json
          rm -f ./ruleset.xml
          rm -f ./stylelint.config.js
          rm -f ./webpack.js

          cd $cwd
          tar -czvf cad_viewer.tar.gz cad_viewer
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cad_viewer
          path: cad_viewer.tar.gz
