name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
permissions:
  actions: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@06d6baf7d8f41934ab630e97d9e6c0bc9c9ac5e4 # v3
        id: versions
        continue-on-error: true
        with:
          fallbackNode: '^24'
          fallbackNpm: '^11.3'

      - name: Setup pnpm
        if: ${{ steps.versions.outputs.nodeVersion }}
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        if: ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}
          cache: 'pnpm'

      - name: Install dependencies
        if: ${{ steps.versions.outputs.nodeVersion }}
        run: pnpm install --frozen-lockfile

      - name: Set up php 8.2
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
        with:
          php-version: 8.2
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check composer.json
        id: check_composer
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: "composer.json"

      - name: Install composer dependencies
        if: steps.check_composer.outputs.files_exists == 'true'
        run: |
          composer install

      - name: Lint code
        run: pnpm run lint
      - name: Build projects
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          make build-js-production
      - name: Run unit tests
        run: make test
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium
      - name: Run E2E tests
        run: pnpm exec playwright test
      - name: Upload Playwright artifacts
        if: failure()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.1
        with:
          name: playwright-artifacts
          path: |
            playwright-report/
            test-results/
          if-no-files-found: ignore
      - name: Package with makefile
        run: make all
