name: Frontend Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vitest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Vitest (Vue Component Tests)
      run: npm run test:component
      continue-on-error: true

  cypress:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        build: npm run build
        start: npm run dev
        wait-on: 'http://localhost:8080'
        browser: chrome
