name: Integration Tests

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: integration-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-latest-low
    outputs:
      php-max: ${{ steps.versions.outputs.php-max }}
    steps:
      - name: Checkout app
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get version matrix
        id: versions
        uses: icewind1991/nextcloud-version-matrix@8a7bac6300b2f0f3100088b297995a229558ddba # v1.3.2

  integration-sqlite:
    runs-on: ubuntu-latest
    needs: matrix
    name: sqlite

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up PHP
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
      with:
        php-version: ${{ needs.matrix.outputs.php-max }}
        extensions: pdo, pdo_sqlite
        coverage: none

    - name: Run SQLite integration tests
      run: php tests/integration/run.php --db=sqlite


  integration-federation:
    runs-on: ubuntu-latest
    needs: matrix
    name: federation

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up PHP
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
      with:
        php-version: ${{ needs.matrix.outputs.php-max }}
        tools: composer:v2
        coverage: none

    - name: Install dependencies
      run: composer install --no-interaction --ignore-platform-reqs
      
    - name: Run federation integration tests
      run: php tests/integration/federation.php
      continue-on-error: true

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [integration-sqlite, integration-federation]
    if: always()
    name: integration-summary

    steps:
    - name: Summary status
      run: |
        if [[ "${{ needs.integration-sqlite.result }}" != "success" ]] && [[ "${{ needs.integration-sqlite.result }}" != "skipped" ]]; then exit 1; fi
        if [[ "${{ needs.integration-federation.result }}" != "success" ]] && [[ "${{ needs.integration-federation.result }}" != "skipped" ]]; then exit 1; fi
