# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Type checking

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  pull_request:
  push:
    branches:
      - main
      - stable*
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: lint-typescript-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    outputs:
      src: ${{ steps.changes.outputs.src }}

    steps:
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - '.github/workflows/lint-typescript.yml'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'tsconfig.json'
              - '**.ts'
              - '**.vue'

      - name: Override for workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "src=true" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest

    needs: changes
    if: needs.changes.outputs.src == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        env:
          CYPRESS_INSTALL_BINARY: 0
        run: |
          pnpm install

      - name: Check types
        run: |
          pnpm run --if-present check-types
          pnpm run --if-present ts:check

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [changes, test]

    if: always()

    name: typescript-summary

    steps:
      - name: Summary status
        run: |
          if [[ "${{ needs.changes.outputs.src }}" != "false" ]]; then
            result="${{ needs.test.result }}"
            if [[ "$result" != "success" && "$result" != "skipped" && -n "$result" ]]; then
              exit 1
            fi
          fi
