# Spreed-style linting workflow
# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Linting

on: pull_request

permissions:
  contents: read

concurrency:
  group: lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest-low
    permissions:
      contents: read
      pull-requests: read

    outputs:
      src: ${{ steps.changes.outputs.src}}

    steps:
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - '.github/workflows/**'
              - '**.php'
              - 'src/**'
              - 'appinfo/info.xml'
              - 'package.json'
              - 'package-lock.json'
              - 'tsconfig.json'
              - '.eslintrc.*'
              - 'css/**'
              - '**.js'
              - '**.ts'
              - '**.vue'

  lint-php:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.src != 'false'
    name: PHP lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none

      - name: Lint PHP
        run: |
          find . -name '*.php' -not -path './vendor/*' -not -path './node_modules/*' -print0 | xargs -0 -n1 php -l

  lint-php-cs:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.src != 'false'
    name: PHP-CS-Fixer

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none

      - name: Install PHP-CS-Fixer
        run: |
          wget -q https://cs.symfony.com/download/php-cs-fixer-v3.phar -O php-cs-fixer
          chmod +x php-cs-fixer

      - name: Run PHP-CS-Fixer
        run: |
          php php-cs-fixer fix --dry-run --diff --rules=@PSR12 .

  lint-eslint:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.src != 'false'
    name: ESLint

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set up npm
        run: npm i -g 'npm@11'

      - name: Install dependencies
        env:
          CYPRESS_INSTALL_BINARY: 0
          PUPPETEER_SKIP_DOWNLOAD: true
        run: npm ci

      - name: Run ESLint
        run: npx eslint src/

  lint-stylelint:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.src != 'false'
    name: Stylelint

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set up npm
        run: npm i -g 'npm@11'

      - name: Install dependencies
        env:
          CYPRESS_INSTALL_BINARY: 0
          PUPPETEER_SKIP_DOWNLOAD: true
        run: npm ci

      - name: Run Stylelint
        run: npx stylelint css/**

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest-low
    needs: [changes, lint-php, lint-php-cs, lint-eslint, lint-stylelint]
    if: always()

    name: lint-summary

    steps:
      - name: Summary status
        run: |
          if [[ "${{ needs.changes.outputs.src }}" != "false" ]]; then
            if [[ "${{ needs.lint-php.result }}" != "success" ]]; then exit 1; fi
            if [[ "${{ needs.lint-php-cs.result }}" != "success" ]]; then exit 1; fi
            if [[ "${{ needs.lint-eslint.result }}" != "success" ]]; then exit 1; fi
            if [[ "${{ needs.lint-stylelint.result }}" != "success" ]]; then exit 1; fi
          fi
