name: PHPUnit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      php-version: ${{ steps.versions.outputs.php-available-list }}
    steps:
      - name: Checkout app
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Get version matrix
        id: versions
        uses: icewind1991/nextcloud-version-matrix@v1.3.2
