# Static analysis workflow
# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Static analysis

on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

concurrency:
  group: psalm-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  psalm:
    runs-on: ubuntu-latest
    name: static-psalm-analysis

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
          ini-file: development
          ini-values: 'error_reporting=E_ALL|E_STRICT'

      - name: Install dependencies
        run: composer install --no-dev --no-interaction

      - name: Install Psalm
        run: composer require --dev vimeo/psalm --no-interaction

      - name: Install nextcloud/ocp
        run: composer require --dev nextcloud/ocp:dev-main --ignore-platform-reqs --with-dependencies --no-interaction

      - name: Run Psalm
        run: vendor/bin/psalm --threads=1 --monochrome --no-progress --output-format=github
