name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      APPSTORE_TOKEN: ${{ secrets.APPSTORE_TOKEN }}
    steps:
      - uses: googleapis/release-please-action@v4.1.3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Debug release outputs
        run: |
          echo "release_created: ${{ steps.release.outputs.release_created }}"
          echo "tag_name: ${{ steps.release.outputs.tag_name }}"
          echo "All outputs: ${{ toJson(steps.release.outputs) }}"

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get app id and version
        if: ${{ steps.release.outputs.release_created }}
        id: app-data
        run: |
          echo "APP_NAME=$(sed -n 's/.*<id>\(.*\)<\/id>.*/\1/p' appinfo/info.xml | xargs)" >> $GITHUB_ENV
          echo "APP_VERSION=$(sed -n 's/.*<version>\(.*\)<\/version>.*/\1/p' appinfo/info.xml | xargs)" >> $GITHUB_ENV
          echo "NC_MIN_VERSION=$(grep -oP '(?<=nextcloud min-version=").*?(?=")' appinfo/info.xml | head -n 1)" >> $GITHUB_ENV

      - name: Read package.json node and npm engines version
        if: ${{ steps.release.outputs.release_created }}
        uses: skjnldsv/read-package-engines-version-actions@06d6baf7d8f41934ab630e97d9e6c0bc9c9ac5e4 # v3
        id: versions
        continue-on-error: true
        with:
          fallbackNode: '^24'
          fallbackNpm: '^11.3'

      - name: Setup pnpm
        if: ${{ steps.release.outputs.release_created && steps.versions.outputs.nodeVersion }}
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        if: ${{ steps.release.outputs.release_created && steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}
          cache: 'pnpm'

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created && steps.versions.outputs.nodeVersion }}
        run: pnpm install --frozen-lockfile

      - name: Get php version
        if: ${{ steps.release.outputs.release_created }}
        id: php-versions
        uses: icewind1991/nextcloud-version-matrix@8a7bac6300b2f0f3100088b297995a229558ddba # v1.3.2
        with:
          filename: appinfo/info.xml

      - name: Set up php ${{ steps.php-versions.outputs.php-min }}
        if: ${{ steps.release.outputs.release_created }}
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: ${{ steps.php-versions.outputs.php-min }}
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install composer dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: composer install --no-dev

      - name: Build projects
        if: ${{ steps.release.outputs.release_created && steps.versions.outputs.nodeVersion }}
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          make production-setup

      - name: Package with makefile
        if: ${{ steps.release.outputs.release_created }}
        run: make all

      - name: Check server download link for ${{ env.NC_MIN_VERSION }}
        if: ${{ steps.release.outputs.release_created && env.APP_PRIVATE_KEY != '' }}
        run: |
          NCVERSION='${{ env.NC_MIN_VERSION }}'
          DOWNLOAD_URL=$(curl -s "https://updates.nextcloud.com/updater_server/latest?channel=beta&version=$NCVERSION" | jq -r '.downloads.zip[0]')
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV

      - name: Download server ${{ env.NC_MIN_VERSION }}
        if: ${{ steps.release.outputs.release_created && env.APP_PRIVATE_KEY != '' && env.DOWNLOAD_URL != 'null' }}
        continue-on-error: true
        id: server-download
        run: |
          echo "Downloading release tarball from $DOWNLOAD_URL"
          wget $DOWNLOAD_URL -O nextcloud.zip
          unzip nextcloud.zip

      - name: Checkout server master fallback
        if: ${{ steps.release.outputs.release_created && env.APP_PRIVATE_KEY != '' && steps.server-download.outcome != 'success' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: true
          repository: nextcloud/server
          path: nextcloud

      - name: Sign app
        if: ${{ steps.release.outputs.release_created && env.APP_PRIVATE_KEY != '' }}
        run: |
          CERT_URL="https://github.com/nextcloud/app-certificate-requests/raw/master/${{ env.APP_NAME }}/${{ env.APP_NAME }}.crt"
          if wget --quiet --spider "$CERT_URL"; then
            echo "Certificate found, proceeding with signing..."
            wget --quiet "$CERT_URL"
            # Extracting release
            cd build/artifacts
            tar -xvf ${{ env.APP_NAME }}.tar.gz
            cd ../../
            # Setting up keys
            echo "${{ env.APP_PRIVATE_KEY }}" > ${{ env.APP_NAME }}.key
            # Signing
            php nextcloud/occ integrity:sign-app --privateKey=./${{ env.APP_NAME }}.key --certificate=./${{ env.APP_NAME }}.crt --path=$(pwd)/build/artifacts/${{ env.APP_NAME }}
            # Rebuilding archives
            cd build/artifacts
            tar -zcvf ${{ env.APP_NAME }}.tar.gz --owner=www-data --group=www-data ${{ env.APP_NAME }}
            zip -r ${{ env.APP_NAME }}.zip ${{ env.APP_NAME }}
          else
            echo "::warning::Certificate not found at $CERT_URL. Skipping signing."
          fi

      - name: Attach app tarball to github release
        if: ${{ steps.release.outputs.release_created }}
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/artifacts/${{ env.APP_NAME }}.tar.gz
          asset_name: ${{ env.APP_NAME }}-${{ steps.release.outputs.tag_name }}.tar.gz
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true

      - name: Attach app zip to github release
        if: ${{ steps.release.outputs.release_created }}
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/artifacts/${{ env.APP_NAME }}.zip
          asset_name: ${{ env.APP_NAME }}-${{ steps.release.outputs.tag_name }}.zip
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true

      - name: Attach source tarball to github release
        if: ${{ steps.release.outputs.release_created }}
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/artifacts/${{ env.APP_NAME }}-source.tar.gz
          asset_name: ${{ env.APP_NAME }}-${{ steps.release.outputs.tag_name }}-source.tar.gz
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true

      - name: Attach source zip to github release
        if: ${{ steps.release.outputs.release_created }}
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/artifacts/${{ env.APP_NAME }}-source.zip
          asset_name: ${{ env.APP_NAME }}-${{ steps.release.outputs.tag_name }}-source.zip
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true

      - name: Upload app to Nextcloud appstore
        if: ${{ steps.release.outputs.release_created && env.APPSTORE_TOKEN != '' && env.APP_PRIVATE_KEY != '' }}
        uses: nextcloud-releases/nextcloud-appstore-push-action@a011fe619bcf6e77ddebc96f9908e1af4071b9c1 # v1.0.3
        with:
          app_name: ${{ env.APP_NAME }}
          appstore_token: ${{ env.APPSTORE_TOKEN }}
          download_url: https://github.com/${{ github.repository }}/releases/download/${{ steps.release.outputs.tag_name }}/${{ env.APP_NAME }}-${{ steps.release.outputs.tag_name }}.tar.gz
          app_private_key: ${{ env.APP_PRIVATE_KEY }}
